export default {
  darkMode: "class",
  theme: {
    extend: {
        "colors": {
                    "outline-variant": "#c0c7d3",
                    "warning": "#F1D832",
                    "on-error-container": "#93000a",
                    "on-secondary-fixed-variant": "#004c6d",
                    "primary": "#005fa0",
                    "on-background": "#191c1e",
                    "on-surface": "#17212B",
                    "on-secondary-container": "#004e70",
                    "on-tertiary-container": "#fffbff",
                    "surface-container-lowest": "#ffffff",
                    "success": "#4CAF50",
                    "surface-tint": "#0061a4",
                    "inverse-primary": "#9fcaff",
                    "surface": "#FFFFFF",
                    "surface-container-low": "#f2f4f6",
                    "primary-container": "#0078c9",
                    "on-tertiary-fixed-variant": "#93000d",
                    "tertiary-fixed": "#ffdad6",
                    "surface-dim": "#d8dadc",
                    "on-primary-fixed": "#001d36",
                    "on-primary": "#ffffff",
                    "secondary-container": "#5ec2fe",
                    "on-secondary-fixed": "#001e2e",
                    "surface-variant": "#e0e3e5",
                    "surface-bright": "#f8f9fb",
                    "primary-fixed-dim": "#9fcaff",
                    "error": "#ED1C24",
                    "neutral-bg": "#F6F8FA",
                    "surface-container-high": "#e6e8ea",
                    "on-primary-container": "#fdfcff",
                    "outline": "#707883",
                    "on-surface-variant": "#404752",
                    "tertiary": "#ED1C24",
                    "on-primary-fixed-variant": "#00497d",
                    "surface-container-highest": "#e0e3e5",
                    "on-error": "#ffffff",
                    "secondary-fixed": "#c7e7ff",
                    "background": "#f8f9fb",
                    "tertiary-fixed-dim": "#ffb4ab",
                    "inverse-surface": "#2d3133",
                    "inverse-on-surface": "#eff1f3",
                    "primary-fixed": "#d1e4ff",
                    "secondary": "#00658f",
                    "on-tertiary": "#ffffff",
                    "on-tertiary-fixed": "#410002",
                    "secondary-fixed-dim": "#86cfff",
                    "tertiary-container": "#e71520",
                    "error-container": "#ffdad6",
                    "surface-container": "#eceef0",
                    "on-secondary": "#ffffff"
            },
        "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "24px",
                    "xl": "32px",
                    "full": "9999px"
            },
        "spacing": {
                    "sm": "8px",
                    "gutter": "24px",
                    "xs": "4px",
                    "md": "16px",
                    "section": "96px",
                    "lg": "24px",
                    "xl": "40px",
                    "xxl": "64px"
            },
        "fontFamily": {
                    "label-md": ["Inter"],
                    "label-lg": ["Inter"],
                    "body-sm": ["Inter"],
                    "body-md": ["Inter"],
                    "headline-md": ["Poppins"],
                    "headline-display-mobile": ["Plus Jakarta Sans"],
                    "headline-display": ["Poppins"],
                    "label-sm": ["Inter"],
                    "headline-lg": ["Poppins"],
                    "body-lg": ["Inter"]
            },
        "fontSize": {
                    "label-md": ["14px", {"lineHeight": "1.2", "fontWeight": "600"}],
                    "label-lg": ["16px", {"lineHeight": "1.2", "fontWeight": "600"}],
                    "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
                    "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                    "headline-md": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                    "headline-display-mobile": ["40px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "headline-display": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "700"}],
                    "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "600"}],
                    "headline-lg": ["48px", {"lineHeight": "1.15", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "body-lg": ["18px", {"lineHeight": "1.7", "fontWeight": "400"}]
            }
    },
  },
  plugins: [],
};